select * from HoaDon
select * from Chuyen
select * from KhachHang
select * from NhanVien
select * from Ga
select * from ChoNgoi
select * from ChiTietKhuyenMai
select * from ChiTietTuyen
select * from ChiTietVe
select * from KhuyenMai
select * from TaiKhoan
select * from Tau
select * from Toa
select * from Tuyen
select * from VE